// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Newtonsoft.Json.Linq;
using System;
using System.Collections;
using System.Linq;
using System.Reflection;
using TaxCalculator.UI.Desktop.Extensions;
using TaxCalculator.UI.MVVM;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.

namespace TaxCalculator.UI.Desktop.Controls.DataGrid
{
    public sealed partial class AutoGeneratedDataGrid : UserControl
    {
        public ICollection DataItems
        {
            get => (ICollection)GetValue(DataItemsProperty);
            set
            {
                SetValue(DataItemsProperty, value);
                GenerateColumns(value);
            }
        }

        public static DependencyProperty DataItemsProperty = DependencyProperty.Register(nameof(DataItems),
            typeof(ICollection),
            typeof(AutoGeneratedDataGrid),
            new PropertyMetadata(null));

        private readonly IColumnFactory _columnFactory;

        public AutoGeneratedDataGrid()
        {
            this.InitializeComponent();

            _columnFactory = App.Current.GetService<IColumnFactory>();
        }

        private void GenerateColumns(ICollection dataItems)
        {
            if (dataItems != null && dataItems.Count > 0 && DataGrid.Columns.Count == 0)
            {
                var type = dataItems.GetType();

                if (type.IsGenericType)
                {
                    var genericArgument = type.GetGenericArguments().First();
                    if (genericArgument.GetGenericTypeDefinition() == typeof(ModelContainer<>))
                    {
                        var firstItem = dataItems.Cast<object>().First();
                        var result = genericArgument.GetProperty(nameof(ModelContainer<object>.Type))?.GetValue(firstItem);

                        if (result is Type modelType)
                        {
                            GenerateColumns(modelType);
                        }
                        else
                        {
                            throw new Exception("Something went wrong during fetching model container type");
                        }
                    }
                    else
                    {
                        GenerateColumns(genericArgument);
                    }
                }
                else
                {
                    throw new Exception("Items should be generic collection");
                }
            }
        }

        private void GenerateColumns(Type modelType)
        {
            var modelProperties = modelType.GetProperties()
                .Where(x => x.GetCustomAttribute<GeneratedColumnAttribute>() != null)
                .ToList();

            foreach (var property in modelProperties)
            {
                var column = _columnFactory.CreateColumn(property);
                DataGrid.Columns.Add(column);
            }
        }
    }
}
